# traefik.yml
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  kafka:
    address: ":9092" # Port TCP pour Kafka
  kafdrop:
    address: ":9002"
providers:
  docker:
    exposedByDefault: false

#certificatesResolvers:
#  letsencrypt:
#    acme:
#      email: votremail@example.com  # Remplacez par votre adresse email
#      storage: /letsencrypt/acme.json
#      httpChallenge:
#        entryPoint: http

#middlewares:
#  auth:
#    basicAuth:
#      users:
#        - "admin:$apr1$vRxRLGBb$f9Aw.9y/znobeCM41NYQV1" 

api:
  insecure: true
sudo lsof -i :80
sudo lsof -i :443



