version: '3.8'
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=vpn.votre-domaine.com      # ⚠️ Remplacez par votre domaine
      - PASSWORD=motdepassefort             # ⚠️ Définissez un mot de passe sécurisé
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.1/24     # Adresse réseau VPN
      - WG_DEFAULT_DNS=10.8.0.2             # Adresse DNS interne (dnsmasq)
    volumes:
      - ./wg-easy-data:/etc/wireguard      # Persistance des données
    ports:
      - "51820:51820/udp"                    # Port WireGuard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      proxy: 
      wg_network:
        ipv4_address: 10.8.0.1

  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
    restart: unless-stopped
    networks:
      wg_network:
        ipv4_address: 10.8.0.2
        
  wg_network:
    external: true
    ipam:
      config:
        - subnet: 10.8.0.0/24
idea@idea:~/Documents/DataOps/WireGuard$ sudo docker compose up
WARN[0000] /home/idea/Documents/DataOps/WireGuard/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 0/2
 ⠋ Container wg-easy  Creating                                                                                                                  0.0s 
 ⠋ Container dnsmasq  Creating                                                                                                                  0.0s 
Error response from daemon: invalid config for network 4b6a15d03c4dc0e565ac93683dd92821a576d22e6a3a8559df631c43a4b3ddca: invalid endpoint settings:
no configured subnet or ip-range contain the IP address 10.8.0.1
