version: '3.8'
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=vpn.votre-domaine.com      # ⚠️ Remplacez par votre domaine
      - PASSWORD=motdepassefort             # ⚠️ Définissez un mot de passe sécurisé
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.1/24     # Adresse réseau VPN
      - WG_DEFAULT_DNS=10.8.0.2             # Adresse DNS interne (dnsmasq)
    volumes:
      - ./wg-easy-data:/etc/wireguard      # Persistance des données
    ports:
      - "51820:51820/udp"                    # Port WireGuard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      proxy: 
      wg_network:
        ipv4_address: 10.8.0.1

  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
    restart: unless-stopped
    networks:
      wg_network:
        ipv4_address: 10.8.0.2
        
  wg_network:
    external: true
    ipam:
      config:
        - subnet: 10.8.0.0/24
[kafka@283b58d18e69 ~]$ /kafka/bin/kafka-topics.sh --list --bootstrap-server 154.120.150.40:9092
[2024-09-23 21:32:12,311] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (/154.120.150.40:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-09-23 21:32:12,416] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (/154.120.150.40:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-09-23 21:32:12,519] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (/154.120.150.40:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-09-23 21:32:12,723] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (/154.120.150.40:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-09-23 21:32:13,229] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (/154.120.150.40:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-09-23 21:32:13,936] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (/154.120.150.40:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2024-09-23 21:32:15,145] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (/154.120.150.40:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
^C[kafka@283b58d18e69 ~]$ 

